<!DOCTYPE HTML>
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $this->title; ?></title>
	<link rel="stylesheet" href="app/assets/css/styles.css">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
	<script src="app/assets/bxslider/js/jquery.bxslider.min.js"></script>
	<link href="app/assets/bxslider/css/jquery.bxslider.css" rel="stylesheet" />
</head>
<body>
<section id="wrap">